export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';
export const CHAT_MESSAGES_REQUEST = 'CHAT_MESSAGES_REQUEST';
export const CHAT_MESSAGES_SUCCESS = 'CHAT_MESSAGES_SUCCESS';
export const CHAT_MESSAGES_FAILURE = 'CHAT_MESSAGES_FAILURE';
export const FRIEND_HISTORY_REQUEST = 'FRIEND_HISTORY_REQUEST';
export const FRIEND_HISTORY_SUCCESS = 'FRIEND_HISTORY_SUCCESS';
export const FRIEND_HISTORY_FAILURE = 'FRIEND_HISTORY_FAILURE';
export const FRIEND_LIST_REQUEST = 'FRIEND_LIST_REQUEST';
export const FRIEND_LIST_SUCCESS = 'FRIEND_LIST_SUCCESS';
export const FRIEND_LIST_FAILURE = 'FRIEND_LIST_FAILURE';
export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';
export const NEW_CHAT_CHANNEL = 'NEW_CHAT_CHANNEL';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_IS_PARTY = 'SET_IS_PARTY';

export const PARTY_LIST_REQUEST = 'PARTY_LIST_REQUEST';
export const PARTY_LIST_SUCCESS = 'PARTY_LIST_SUCCESS';
export const PARTY_LIST_FAILURE = 'PARTY_LIST_FAILURE';
export const PARTY_HISTORY_REQUEST = 'PARTY_HISTORY_REQUEST';
export const PARTY_HISTORY_SUCCESS = 'PARTY_HISTORY_SUCCESS';
export const PARTY_HISTORY_FAILURE = 'PARTY_HISTORY_FAILURE';
export const ADD_PARTY_REQUEST = 'ADD_PARTY_REQUEST';
export const ADD_PARTY_SUCCESS = 'ADD_PARTY_SUCCESS';
export const ADD_PARTY_FAILURE = 'ADD_PARTY_FAILURE';

export const UBER_EMAIL = 'uber_aid@party.io';
export const OPENTABLE_EMAIL = 'opentable_aid@party.io';
export const UBER_USERNAME = 'uber_aid';
export const OPENTABLE_USERNAME = 'opentable_aid';
export const BOTLIST = ['uber_aid', 'opentable_aid'];

